#!/bin/sh

set -e

# . /usr/share/debconf/confmodule

# DB_HOST=""
# DB_NAME=""
# DB_USER=""
# DB_PWD=""
# DEFAULT_CONFIG="/etc/onlyoffice/documentserver/default.json"

# apply_connection_string(){
	# if [ -d /var/www/onlyoffice/ ]; then
		# bomstrip < $DEFAULT_CONFIG | \
			# json -e "this.services.CoAuthoring.sql.host = \"$DB_HOST\"" | \
			# json -e "this.services.CoAuthoring.sql.database = \"$DB_NAME\"" | \
			# json -e "this.services.CoAuthoring.sql.user = \"$DB_USER\"" | \
			# json -e "this.services.CoAuthoring.sql.pass = \"$DB_PWD\"" > $DEFAULT_CONFIG
	# fi
# }

# db_input medium onlyoffice/db-host || true
# db_input medium onlyoffice/db-name || true
# db_input medium onlyoffice/db-user || true
# db_go

# db_input critical onlyoffice/db-pwd || true
# db_go

# db_get onlyoffice/db-host
# DB_HOST="$RET"

# db_get onlyoffice/db-name
# DB_NAME="$RET"

# db_get onlyoffice/db-user
# DB_USER="$RET"

# db_get onlyoffice/db-pwd
# DB_PWD="$RET"

# # apply_connection_string

exit 0
