../../common/documentserver/bin/*.sh usr/bin/
../../common/documentserver/config/* etc/onlyoffice/documentserver/
../../common/documentserver/home/* var/www/onlyoffice/documentserver/
../../common/documentserver/nginx/*.template etc/nginx/conf.d/
../../common/documentserver/nginx/includes/* etc/nginx/includes/
../../common/documentserver/supervisor/* etc/supervisor/conf.d/
../../common/fonts/* usr/share/fonts/truetype/
