../../common/documentserver/bin/*.sh usr/bin/
../../common/documentserver/config/* etc/onlyoffice/documentserver/
../../common/documentserver/home/* var/www/onlyoffice/documentserver/
../../common/documentserver/nginx/* etc/onlyoffice/documentserver/nginx/
../../common/documentserver/supervisor/* etc/onlyoffice/documentserver/supervisor/
../../common/documentserver/logrotate/* etc/onlyoffice/documentserver/logrotate/
